vim:fileencoding=utf-8:foldmethod=marker

Fonts {
  font_family      FiraCode Nerd Font
  bold_font        FiraCode Nerd Font Black
  italic_font      FiraCode Nerd Font ExtLt Italic
  bold_italic_font FiraCode Nerd Font Black Italic
}

# Catppuccin-Mocha
include   Catppuccin-Mocha.conf

# title bar / window
background_opacity      0.98
background_blur         30
window_padding_width    1
draw_minimal_borders    yes
hide_window_decorations no
titlebar-only           yes
# active_border_color     none

# misc
allow_remote_control       y
strip_trailing_spaces      smart
dynamic_background_opacity True

# tab bar
tab_bar_align              center
tab_bar_edge               bottom
tab_bar_style              fade
tab_activity_symbol        👺
tab_bar_min_tabs           2
tab_powerline_style        angled
tab_separator              " "
tab_title_template         {activity_symbol} {title} {fmt.fg.blue}{fmt.bold}

# sys
update_check_interval      6.0
shell                      zsh
editor                     nvim
