# Enable instant prompt (makes shell start faster)
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Plugins
source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Environment variables
export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH
export TERMINAL=kitty
export TERM=xterm-kitty
export EDITOR="nvim"
export VISUAL="nvim"
export LS_COLORS="$(vivid generate catppuccin-mocha)"

# Aliases
alias terminal='kitty'
alias s='TERM=xterm-256color kitten ssh'
alias ls='eza --icons -h'
alias la='eza --icons -lah'
alias lt='eza --icons --tree -h'
alias l='eza --icons -lh'

# Load p10k config (generated by p10k configure)
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh
